import Foundation
import SwiftUI

public struct ColorFileGenerator: Sendable {

    public init() {}

    public func generateCode(entries: [ColorEntry]) -> String {
        var code = """
        // Auto-generated by Sheet — do not edit
        // Generated on: \(Date().formatted(date: .abbreviated, time: .shortened))

        import SwiftUI

        public extension Color {
        """

        for entry in entries {
            let safeName = entry.name.replacingOccurrences(of: " ", with: "") // Simple sanitization for now
            code += """

            /// \(entry.name)
            static var \(safeName): Color {
                Color(ColorName.\(safeName))
            }
            """
        }

        code += """
        }

        public enum ColorName: String {
        """

        for entry in entries {
            let safeName = entry.name.replacingOccurrences(of: " ", with: "")
            code += """
            case \(safeName)
            """
        }
        code += """
        }
        """
        return code
    }
}
