import Foundation
import SwiftUI

#if canImport(AppKit)
import AppKit
#endif

#if canImport(UIKit)
import UIKit
#endif

public struct ColorDynamicFileGenerator: Sendable {

    public init() {}

    public func generateCode() -> String {
        var lines: [String] = []
        lines.reserveCapacity(200)
        let formattedDate = Date().formatted(date: .abbreviated, time: .shortened)
        
        lines.append("// Auto-generated by Sheet — do not edit")
        lines.append("// Generated on: \(formattedDate)")
        lines.append("")
        
        lines.append("import SwiftUI\n\n")
        lines.append("#if canImport(AppKit)\n")
        lines.append("import AppKit\n")
        lines.append("#endif\n\n")
        lines.append("#if canImport(UIKit)\n")
        lines.append("import UIKit\n")
        lines.append("#endif\n\n")
        
        lines.append("extension Color {\n")
        lines.append("    init(any color: Color) {\n")
        lines.append("        #if canImport(UIKit)\n")
        lines.append("        self.init(uiColor: UIColor(color))\n")
        lines.append("        #else\n")
        lines.append("        self.init(nsColor: NSColor(color))\n")
        lines.append("        #endif\n")
        lines.append("    }\n\n")
        
        lines.append("    #if canImport(UIKit)\n")
        lines.append("    init(any color: UIColor) {\n")
        lines.append("        self.init(uiColor: color)\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
        
        lines.append("    #if canImport(AppKit)\n")
        lines.append("    init(any color: NSColor) {\n")
        lines.append("        self.init(nsColor: color)\n")
        lines.append("    }\n")
        lines.append("    #endif\n")
        lines.append("}\n\n")
        
        lines.append("extension Color {\n")
        lines.append("    init(any: Color, dark: Color) {\n")
        lines.append("        #if canImport(UIKit)\n")
        lines.append("        self.init(any: UIColor(any), dark: UIColor(dark))\n")
        lines.append("        #else\n")
        lines.append("        self.init(any: NSColor(any), dark: NSColor(dark))\n")
        lines.append("        #endif\n")
        lines.append("    }\n\n")
        
        addAnyDarkUIKit(to: &lines)
        addAnyDarkAppKit(to: &lines)
        
        lines.append("}\n\n")
        
        lines.append("extension Color {\n")
        lines.append("    init(any: Color, light: Color, dark: Color) {\n")
        lines.append("        #if canImport(UIKit)\n")
        lines.append("        self.init(any: UIColor(any), light: UIColor(light), dark: UIColor(dark))\n")
        lines.append("        #else\n")
        lines.append("        self.init(any: NSColor(any), light: NSColor(light), dark: NSColor(dark))\n")
        lines.append("        #endif\n")
        lines.append("    }\n\n")
        
        addAnyLightDarkUIKit(to: &lines)
        addAnyLightDarkAppKit(to: &lines)
        
        lines.append("}\n\n")
        
        lines.append("extension Color {\n")
        lines.append("    init(light: Color, dark: Color) {\n")
        lines.append("        #if canImport(UIKit)\n")
        lines.append("        self.init(light: UIColor(light), dark: UIColor(dark))\n")
        lines.append("        #else\n")
        lines.append("        self.init(light: NSColor(light), dark: NSColor(dark))\n")
        lines.append("        #endif\n")
        lines.append("    }\n\n")
        
        addLightDarkUIKit(to: &lines)
        addLightDarkAppKit(to: &lines)
        
        lines.append("}\n")
        
        return lines.joined(separator: "\n")
    }
    
    private func addAnyDarkUIKit(to lines: inout [String]) {
        lines.append("    #if canImport(UIKit)\n")
        lines.append("    init(any: UIColor, dark: UIColor) {\n")
        lines.append("        #if os(watchOS)\n")
        lines.append("        self.init(uiColor: dark)\n")
        lines.append("        #else\n")
        lines.append("        self.init(uiColor: UIColor { traits in\n")
        lines.append("            switch traits.userInterfaceStyle {\n")
        lines.append("            case .light, .unspecified:\n")
        lines.append("                return any\n")
        lines.append("            case .dark:\n")
        lines.append("                return dark\n")
        lines.append("            @unknown default:\n")
        lines.append("                assertionFailure(\"Unknown userInterfaceStyle: \\(traits.userInterfaceStyle)\")\n")
        lines.append("                return any\n")
        lines.append("            }\n")
        lines.append("        })\n")
        lines.append("        #endif\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
    }
    
    private func addAnyDarkAppKit(to lines: inout [String]) {
        lines.append("    #if canImport(AppKit)\n")
        lines.append("    init(any: NSColor, dark: NSColor) {\n")
        lines.append("        self.init(nsColor: NSColor(name: nil) { appearance in\n")
        lines.append("            switch appearance.name {\n")
        lines.append("            case .aqua,\n")
        lines.append("                 .vibrantLight,\n")
        lines.append("                 .accessibilityHighContrastAqua,\n")
        lines.append("                 .accessibilityHighContrastVibrantLight:\n")
        lines.append("                return any\n")
        lines.append("            case .darkAqua,\n")
        lines.append("                 .vibrantDark,\n")
        lines.append("                 .accessibilityHighContrastDarkAqua,\n")
        lines.append("                 .accessibilityHighContrastVibrantDark:\n")
        lines.append("                return dark\n")
        lines.append("            default:\n")
        lines.append("                assertionFailure(\"Unknown appearance: \\(appearance.name)\")\n")
        lines.append("                return any\n")
        lines.append("            }\n")
        lines.append("        })\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
    }
    
    private func addAnyLightDarkUIKit(to lines: inout [String]) {
        lines.append("    #if canImport(UIKit)\n")
        lines.append("    init(any: UIColor, light: UIColor, dark: UIColor) {\n")
        lines.append("        #if os(watchOS)\n")
        lines.append("        self.init(uiColor: dark)\n")
        lines.append("        #else\n")
        lines.append("        self.init(uiColor: UIColor { traits in\n")
        lines.append("            switch traits.userInterfaceStyle {\n")
        lines.append("            case .light:\n")
        lines.append("                return light\n")
        lines.append("            case .dark:\n")
        lines.append("                return dark\n")
        lines.append("            case .unspecified:\n")
        lines.append("                return any\n")
        lines.append("            @unknown default:\n")
        lines.append("                assertionFailure(\"Unknown userInterfaceStyle: \\(traits.userInterfaceStyle)\")\n")
        lines.append("                return any\n")
        lines.append("            }\n")
        lines.append("        })\n")
        lines.append("        #endif\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
    }
    
    private func addAnyLightDarkAppKit(to lines: inout [String]) {
        lines.append("    #if canImport(AppKit)\n")
        lines.append("    init(any: NSColor, light: NSColor, dark: NSColor) {\n")
        lines.append("        self.init(nsColor: NSColor(name: nil) { appearance in\n")
        lines.append("            switch appearance.name {\n")
        lines.append("            case .aqua,\n")
        lines.append("                 .vibrantLight,\n")
        lines.append("                 .accessibilityHighContrastAqua,\n")
        lines.append("                 .accessibilityHighContrastVibrantLight:\n")
        lines.append("                return light\n")
        lines.append("            case .darkAqua,\n")
        lines.append("                 .vibrantDark,\n")
        lines.append("                 .accessibilityHighContrastDarkAqua,\n")
        lines.append("                 .accessibilityHighContrastVibrantDark:\n")
        lines.append("                return dark\n")
        lines.append("            default:\n")
        lines.append("                assertionFailure(\"Unknown appearance: \\(appearance.name)\")\n")
        lines.append("                return any\n")
        lines.append("            }\n")
        lines.append("        })\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
    }
    
    private func addLightDarkUIKit(to lines: inout [String]) {
        lines.append("    #if canImport(UIKit)\n")
        lines.append("    init(light: UIColor, dark: UIColor) {\n")
        lines.append("        #if os(watchOS)\n")
        lines.append("        self.init(uiColor: dark)\n")
        lines.append("        #else\n")
        lines.append("        self.init(uiColor: UIColor { traits in\n")
        lines.append("            switch traits.userInterfaceStyle {\n")
        lines.append("            case .light, .unspecified:\n")
        lines.append("                return light\n")
        lines.append("            case .dark:\n")
        lines.append("                return dark\n")
        lines.append("            @unknown default:\n")
        lines.append("                assertionFailure(\"Unknown userInterfaceStyle: \\(traits.userInterfaceStyle)\")\n")
        lines.append("                return light\n")
        lines.append("            }\n")
        lines.append("        })\n")
        lines.append("        #endif\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
    }
    
    private func addLightDarkAppKit(to lines: inout [String]) {
        lines.append("    #if canImport(AppKit)\n")
        lines.append("    init(light: NSColor, dark: NSColor) {\n")
        lines.append("        self.init(nsColor: NSColor(name: nil) { appearance in\n")
        lines.append("            switch appearance.name {\n")
        lines.append("            case .aqua,\n")
        lines.append("                 .vibrantLight,\n")
        lines.append("                 .accessibilityHighContrastAqua,\n")
        lines.append("                 .accessibilityHighContrastVibrantLight:\n")
        lines.append("                return light\n")
        lines.append("            case .darkAqua,\n")
        lines.append("                 .vibrantDark,\n")
        lines.append("                 .accessibilityHighContrastDarkAqua,\n")
        lines.append("                 .accessibilityHighContrastVibrantDark:\n")
        lines.append("                return dark\n")
        lines.append("            default:\n")
        lines.append("                assertionFailure(\"Unknown appearance: \\(appearance.name)\")\n")
        lines.append("                return light\n")
        lines.append("            }\n")
        lines.append("        })\n")
        lines.append("    }\n")
        lines.append("    #endif\n\n")
    }
}
