import Foundation
import SwiftUI

#if canImport(UIKit)
import UIKit
#endif

public struct ColorDynamicFileGenerator: Sendable {

    public init() {}

    public func generateCode() -> String {
        let code = """
        // Auto-generated by Sheet — do not edit
        // Generated on: \(Date().formatted(date: .abbreviated, time: .shortened))

        import SwiftUI
        #if canImport(UIKit)
        import UIKit
        #endif

        public extension Color {
            init(_ name: ColorName) {
                self.init(uiColor: UIColor(named: name.rawValue) ?? .clear)
            }
        }

        public extension UIColor {
            convenience init?(hex: String) {
                let r, g, b, a: CGFloat

                if hex.hasPrefix("#") {
                    let start = hex.index(hex.startIndex, offsetBy: 1)
                    let hexColor = String(hex[start...])

                    if hexColor.count == 6 {
                        let scanner = Scanner(string: hexColor)
                        var hexNumber: UInt64 = 0

                        if scanner.scanHexInt64(&hexNumber) {
                            r = CGFloat((hexNumber & 0xff0000) >> 16) / 255
                            g = CGFloat((hexNumber & 0x00ff00) >> 8) / 255
                            b = CGFloat(hexNumber & 0x0000ff) / 255
                            a = 1.0

                            self.init(red: r, green: g, blue: b, alpha: a)
                            return
                        }
                    } else if hexColor.count == 8 {
                        let scanner = Scanner(string: hexColor)
                        var hexNumber: UInt64 = 0

                        if scanner.scanHexInt64(&hexNumber) {
                            r = CGFloat((hexNumber & 0xff000000) >> 24) / 255
                            g = CGFloat((hexNumber & 0x00ff0000) >> 16) / 255
                            b = CGFloat((hexNumber & 0x0000ff00) >> 8) / 255
                            a = CGFloat(hexNumber & 0x000000ff) / 255

                            self.init(red: r, green: g, blue: b, alpha: a)
                            return
                        }
                    }
                }
                return nil
            }

            convenience init(light: String, dark: String) {
                self.init { traitCollection in
                    if traitCollection.userInterfaceStyle == .dark {
                        return UIColor(hex: dark) ?? UIColor(hex: light) ?? .clear
                    } else {
                        return UIColor(hex: light) ?? UIColor(hex: dark) ?? .clear
                    }
                }
            }

            convenience init(any: String) {
                self.init(hex: any) ?? .clear
            }
        }
        """
        return code
    }
}
